### ISSUE TITLE
cb not a function?

### ISSUE THREAD

**Issue by vmkfx** [leanderlee/questrade#1]
edit: i was able to get it working I wasn't doing it right the first time.

  qt.getPositions(function(res, err) {
      res.positions.forEach( function(p){
        console.log(p.symbol);
      });
  });

if (!response.quotes) return cb({ message: 'quote_not_found', symbol: id });
                                 ^

TypeError: cb is not a function

I get a few of these cb not a function errors when trying to run it. I am using the latest Node 7.5 on Windows 10. Am I using the wrong version?

**Comment by Emanuelboi** [comment]
Hi,

I'm running into the same issue (cb is not a function). How were you able to get it done?

Thanks!
