### ISSUE TITLE
Update to ES6+ and linter

### ISSUE THREAD

**Issue by leanderlee** [leanderlee/questrade#10]
`var`s went out of style a long time ago, and the code would look much nicer if it was modernized.

**Comment by hexonet-private** [comment]
Yes, I agree! My linter was all over the place.
Also, with ES6 there are classes construct instead of prototype (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes). Also will make it look nicer

**Comment by lucasvall** [comment]
Yes, I agree! My linter was all over the place.
Also, with ES6 there are classes construct instead of prototype (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes). Also will make it look nicer

**Comment by gwenevieve** [comment]
Is this being worked on?

**Comment by leanderlee** [comment]
Not currently, happy to review PRs though!

**Comment by gwenevieve** [comment]
If you're happy to review PRs (as I'm not too familiar with ES6 yet!), I can probably give it a shot.

**Comment by sebastien-st-amour** [comment]
is this being looked at? I can make a PR with eslint auto fixes
