### ISSUE TITLE
getQuote returns "Request is out of allowed OAuth scopes"

### ISSUE THREAD

**Issue by lucacataldo** [leanderlee/questrade#15]
When calling getQuote(), a "quote_not_found" message is returned despite attempts with both the stock symbol and symbolId. Looking at the method, this is because the response does not contain the "quotes" array. The response, however, does contain a more specific error: "Request is out of allowed OAuth scopes".

Additionally, the QT api docs state that requests to /markets/quote/ are made using the stockId, but the getQuote() method does so using the stock symbol. Not sure if this is related to the issue at hand, but still worth noting.

**Comment by jonathanbell** [comment]
I've noticed that (in the past, at least) `/markets/quote` accepts a single stock symbol or a QGT stock ID.

**Comment by lucacataldo** [comment]
In case anyone is having the same issue:

Went back to a project I was building with this and it turns out it was simply an unchecked box in my api settings. No issue with the library
