### ISSUE TITLE
I'm getting error

### ISSUE THREAD

**Issue by wdumlao** [leanderlee/questrade#2]
xfs.mkdirSync is not a function. Any ideas? Do you also know why the APIs can't resolve OPTIONS method for preflight calls?

**Comment by leanderlee** [comment]
OPTIONS is usually used to check CORS... This is not compatible on the browser.

With regard to the mkdirSync problem, what version of node are you using? Maybe there was an API change.

**Comment by wdumlao** [comment]
I see so I would need to make API requests from say a server? 

Node version v6.10.3 btw. You have been more help than the users in the community forums.


Thanks for all your help

**Comment by leanderlee** [comment]
Yes, you need to make the API requests from node.

This library should be working with node 6, if you have code on how to reproduce the error, please let me know!

**Comment by wdumlao** [comment]
Thanks for your response. I think the fs module was merged with node. Not really sure, but I can provide more once I can provide a way to replicate.

Also if this is server side how do you handle the auth tokens?

**Comment by leanderlee** [comment]
You can provide your account auth token or save it in a text file for node to read.

See from README:
```js
var qt = new Questrade('<your-api-key-here>');
// - OR -
var qt = new Questrade('./path/to/file'); // Location of a text file with the API key
```

**Comment by NimishVerma** [comment]
The error can be reproduced by using 
`var qt = new Questrade('<your-api-key-here>');`
in a React app component. The only way to deal with this is to perform connection in express?
