### ISSUE TITLE
I keep getting "failed_to_refresh_key" every so often

### ISSUE THREAD

**Issue by rb28z2** [leanderlee/questrade#21]
I'm not sure if it's something I'm doing wrong, but every so often (once a day) I get the following error message:

```
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({ message: 'failed_to_refresh_key',
  details:
   { message: 'login_failed',
     token: '<snipped>',
     details: 'Bad Request' } })
    at Questrade.emit (events.js:187:17)
    at Questrade.EventEmitter.emit (domain.js:448:20)
```

Any idea why this is happening and what I can do to prevent it? The solution so far for me is to generate a new API key from Questrade, but its not exactly practical.

**Comment by geggleto** [comment]
this is basically the solution from QT. The key you exchange for has a limited lifespan and if you don't use it to refresh then you have to start the hole process over again :\ it seems to be by design
